// AUTH
export const AUTH_SIGN_IN_REQUEST = '@auth/SIGN_IN_REQUEST';
export const AUTH_SIGN_IN_SUCCESS = '@auth/SIGN_IN_SUCCESS';
export const AUTH_SIGN_UP_REQUEST = '@auth/SIGN_UP_REQUEST';
export const AUTH_SIGN_FAILURE = '@auth/SIGN_FAILURE';
export const AUTH_SIGN_OUT = '@auth/SIGN_OUT';

// USER
export const USER_UPDATE_PROFILE_REQUEST = '@user/UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = '@user/UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAILURE = '@user/UPDATE_PROFILE_FAILURE';
